### ISSUE TITLE
Missing iframe resize when adding comments

### ISSUE THREAD

**Issue by otacke** [NDLANO/h5p-order-priority#12]
## Description
When adding comments to an order item, the text input field that is added increases the height of the content, but it doesn't resize the H5P iframe which will lead to content being cut off at the bottom. The effect worsens if the comment fields receives a line break.

## Steps to reproduce
1. Open "Priority" content.
2. Sort item to the list.
3. Click on "comment" icon -> Notice that the content is cut off at the bottom.
4. Access the text input field for the comment and hit the `enter` key a couple of times -> Notice that the content is cut off even further.

## Background
H5P core cannot automatically detect changes in height, so the content type needs to inform H5P core that it should resize the iframe according to the current content height. That's done by calling `trigger('resize')` on the main class (here `Wrapper`) by means of preference (e.g. passing as prop, callbacks, hook).

**Comment by janlindso** [comment]
Thanks for reporting! This should be working fine now!
